### PR TITLE
Add option to associate spec scores with equipment sets

### PR DESCRIPTION
**Pull request by Lleafll**
This will let users assign equipment sets to spec scores. When comparing items the tooltip then refers to the particular item in the equipment set instead of the currently equipped one.

### CODE REVIEW

**Comment by Necroskillz** [comment]
thx, i will take a look at merging it next week. could you pls fix tabs/spaces? (project-wide indent is 4 spaces)

**Comment by Lleafll** [comment]
My admittedly horrendous indentation is now fixed.

**Comment by Necroskillz** [comment]
it's still wrong tho, sometime there are 2 spaces instead of 4 :D

**Comment by Lleafll** [comment]
Well, I'm used to 2 spaces.

**Comment by Necroskillz** [comment]
merged in commit d300af189960bf4d5dfb0901e1cc3d84a27ec5d3. I added a message so you know when it compares to an item that you currently don't have equipped.

**Pull request closed without merging**
